services:


  kafka:
    image: confluentinc/cp-kafka:7.9.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1j4LnK234-jf43k--x86sw'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      #List of brokers that will work as controllers (1 controller at a time), if we want a backup controller id@kafka:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # = 1 - 1 copy no backup
      # default = 3 (For a cluster of 3 nodes)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Open 2 doors, one in 9092 (clients)
      #               one in 9093 (cluster communication)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0.9092,CONTROLLER://0.0.0.0:9093
      #Defines the addresses that kafka tells clients/brokers to connect to
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost.9092
      KAFKA_CONTROLLER_LISTENERS_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka_kraft:/var/lib/kafka/data



#services:
#  app:
#    build: .
#    container_name: mlogistics-app
#    ports:
#      - "8080:8080"
#    environment:
#      # ⚠️ Fake credentials for development/testing only (docker build) — override with real env vars in production
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mlogisticsdb
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-Hd3vP@ss!xK9mRv4}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-Hd3vP@ss!xK9mRv4}
#      SPRING_PROFILES_ACTIVE: docker
#      JWT_KEY: ${JWT_KEY:-JEdNgp6b8YixKZW3q0DrLPaanmgPafBlsEBpq4PcPYVxFLZ9B94HvlFbOawfnruE}
#    depends_on:
#      db:
#        condition: service_healthy
#
#  db:
#    image: postgres:16
#    container_name: logistics_project
#    environment:
#      # ⚠️ Fake credentials for development/testing only (docker build) — override with real env vars in production
#      POSTGRES_USER: ${POSTGRES_USER:-Hd3vP@ss!xK9mRv4}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Hd3vP@ss!xK9mRv4}
#      POSTGRES_DB: mlogisticsdb
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#      - ./docker/init:/docker-entrypoint-initdb.d
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-Hd3vP@ss!xK9mRv4} -d mlogisticsdb"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
volumes:
  pg_data:
  kafka_kraft:
