spring.application.name=mlogistics
spring.config.import=optional:file:env.properties
server.servlet.context-path=/mlogistics/api/v1
jwt.secret=${JWT_KEY}
# Uses SPRING_DATASOURCE_URL if exists (Docker), otherwise falls back to POSTGRES_DB_LOCAL (local)
spring.datasource.url=${SPRING_DATASOURCE_URL:${POSTGRES_DB_LOCAL}}
# Uses SPRING_DATASOURCE_USERNAME if exists (Docker), otherwise falls back to POSTGRES_USER (local)
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
# Uses SPRING_DATASOURCE_PASSWORD if exists (Docker), otherwise falls back to POSTGRES_PASSWORD (local)
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.web.error.include-message=always

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=mlogistics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer